#!/usr/bin/env bash

# install git
apt-get install git -y
apt-get install python-imaging -y

# packages needed by papirus-temp
apt-get install bc i2c-tools -y

#git clone https://github.com/PiSupply/PaPiRus.git
cd PaPiRus
sudo python setup.py install    # Install PaPirRus python library
papirus-setup    # Install drivers and setup epaper
